<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MySubjectsNewSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $subjects = [
        [
            'title' => 'Fundamentals of Nursing-I',
            'code' => 'NU-101',
            'course_fee' => 0,
            'full_mark_theory' => 75,
            'pass_mark_theory' => 45,
            'full_mark_practical' => 25,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Microbiology',
            'code' => 'NU-102',
            'course_fee' => 0,
            'full_mark_theory' => 50,
            'pass_mark_theory' => 30,
            'full_mark_practical' => 0, // No practical marks explicitly listed, assuming 0 or combined
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Anatomy & Physiology-I',
            'code' => 'NU-103',
            'course_fee' => 0,
            'full_mark_theory' => 75,
            'pass_mark_theory' => 45,
            'full_mark_practical' => 25,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Biochemistry',
            'code' => 'NU-104',
            'course_fee' => 0,
            'full_mark_theory' => 50,
            'pass_mark_theory' => 30,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Functional English',
            'code' => 'NU-105',
            'course_fee' => 0,
            'full_mark_theory' => 75,
            'pass_mark_theory' => 45,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Information & Communication Technology',
            'code' => 'NU-106',
            'course_fee' => 0,
            'full_mark_theory' => 50,
            'pass_mark_theory' => 30,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Ideology & Constitution of Pakistan',
            'code' => 'NU-107',
            'course_fee' => 0,
            'full_mark_theory' => 50,
            'pass_mark_theory' => 30,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'FUNDAMENTALS OF NURSING-II',
            'code' => 'NU-151',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0, // No explicit practical marks given, assuming 0
            'pass_mark_practical' => 0,
            'credit_hour' => 4,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ANATOMY AND PHYSIOLOGY-II',
            'code' => 'NU-152',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'COMMUNITY HEALTH NURSING-I',
            'code' => 'NU-153',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'APPLIED NUTRITION',
            'code' => 'NU-154',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 1,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English-II',
            'code' => 'NU-155',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ISLAMIAT',
            'code' => 'NU-156',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'PAKISTAN STUDIES',
            'code' => 'NU-157',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ADULT HEALTH NURSING-I',
            'code' => 'NU-201',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 8,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'PATHOPHYSIOLOGY-I',
            'code' => 'NU-202',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'HEALTH ASSESSMENT-I',
            'code' => 'NU-203',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'PHARMACOLGY-I',
            'code' => 'NU-204',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'MATHEMATICS',
            'code' => 'NU-205',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 1,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ENGLISH-III',
            'code' => 'NU-206',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ADULT HEALTH NURSING-II',
            'code' => 'NU-251',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 8,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'PATHOPHYSIOLOGY-II',
            'code' => 'NU-252',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'HEALTH ASSESSMENT-II',
            'code' => 'NU-253',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'DEVELOPMENTAL PSYCHOLOGY',
            'code' => 'NU-254',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'PHARMACOLGY-II',
            'code' => 'NU-255',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ENGLISH-IV',
            'code' => 'NU-256',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'NURSING ETHICS-COURSE',
            'code' => 'NU-257',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 1,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'PAEDIATRIC HEALTH NURSING',
            'code' => 'NU-301',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 7,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'COMMUNITY HEALTH NURSING-II',
            'code' => 'NU-302',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 6,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'TEACHING/LEARNING PRINCIPLES',
            'code' => 'NU-303',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English-V',
            'code' => 'NU-304',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'MENTAL HEALTH NURSING',
            'code' => 'NU-351',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 6,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'INTRODUCTION TO BIOSTATISTICS',
            'code' => 'NU-352',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'BEHAVIORAL PSYCHOLOGY',
            'code' => 'NU-353',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'EPIDEMIOLOGY',
            'code' => 'NU-354',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'ENGLISH VI (ACADEMIC WRITING)',
            'code' => 'NU-355',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'CULTURE HEALTH AND SOCIETY',
            'code' => 'NU-356',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Critical Care Nursing',
            'code' => 'NU-401',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 7,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Nursing Theories',
            'code' => 'NU-402',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Leadership & Management in Nursing',
            'code' => 'NU-403',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Nursing Research',
            'code' => 'NU-404',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English-VII (Professional Writing)',
            'code' => 'NU-405',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Community Health Nursing-III',
            'code' => 'NU-451',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 5,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Nursing Seminar / role transition',
            'code' => 'NU-452',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Clinical Practicum',
            'code' => 'NU-453',
            'course_fee' => 0,
            'full_mark_theory' => 0, // Clinical Practicum likely has no theory component
            'pass_mark_theory' => 0,
            'full_mark_practical' => 70, // Assuming full marks are from the 'Final Exam Marks' which would apply to practical
            'pass_mark_practical' => 0,
            'credit_hour' => 5,
            'sub_type' => 'Compulsary',
            'class_type' => 'Practical',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Biochemistry',
            'code' => 'SC-611',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Advance Concepts in Nursing I (Adult Health Nursing)',
            'code' => 'NU-612',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 4,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Health Assessment',
            'code' => 'NU-613',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Pharmacology',
            'code' => 'SC-614',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English I (Functional)',
            'code' => 'EN-615',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Computer Skills & Information Technology',
            'code' => 'CS-616',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => '* Advance Concepts in Nursing (II) Mental Health',
            'code' => 'NU-621',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 4,
            'sub_type' => 'Compulsary',
            'class_type' => 'Both',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Introduction to Biostatistics',
            'code' => 'SC-622',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Epidemiology',
            'code' => 'SC-623',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Culture Health & Society',
            'code' => 'HU-624',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Introduction to Nursing Models & Theories',
            'code' => 'NU-625',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English II (Academics)',
            'code' => 'EN-626',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Principle of Teaching and Clinical Preceptor ship',
            'code' => 'NU-627',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Advance Concepts III (CHN)',
            'code' => 'NU-631',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 4,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Introduction to Nursing Research',
            'code' => 'SC-632',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Professional Development and Ethics',
            'code' => 'NU-633',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Pak Studies',
            'code' => 'PS-634',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Leadership and Management',
            'code' => 'NU-634', // Note: Duplicate code with PS-634
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 3,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English III (Professional writing)',
            'code' => 'EN-635',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Research/Evidence based Elective project',
            'code' => 'NU-641',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 4,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Clinical Practicum',
            'code' => 'NU-642',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0, // Assuming practical marks are not explicitly separated in source data, so defaulting to 0 for this field
            'pass_mark_practical' => 0,
            'credit_hour' => 6,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory', // This seems like a mismatch if it's "Clinical Practicum" but "Theory" class_type
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'English IV (Scholarly writing)',
            'code' => 'EN-643',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
        [
            'title' => 'Islamic Studies/Ethics (For Non-Muslims)',
            'code' => 'IS-644/ET-644',
            'course_fee' => 0,
            'full_mark_theory' => 70,
            'pass_mark_theory' => 0,
            'full_mark_practical' => 0,
            'pass_mark_practical' => 0,
            'credit_hour' => 2,
            'sub_type' => 'Compulsary',
            'class_type' => 'Theory',
            'staff_id' => null,
            'description' => null,
            'created_by' => 1,
            'last_updated_by' => null,
            'status' => 1,
        ],
    ];
    foreach ($subjects as $subject) {
        DB::table('subjects')->insert($subject);
    }

    }
}
